# default development profile
spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    in-memory: false
  #jms:
  #  template:
  #    default-destination: mailbox
  
 