# default development profile
spring:
  profiles:
    active:
    - dev
  thymeleaf:
    cache: false 
  datasource:
    url: jdbc:mysql://localhost:55555/tacoappdb
    username: tacoappuser
    password: tacoapppass
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: false
      # properties.dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    
  #h2:
  #  console:
  #    enabled: true
  #    path: "/h2-console"

logging:
  level:
    root: INFO
    com.example: DEBUG

taco:
  order:
    page-size: 5
  
# prod profile
# ---
# spring:
#  profiles: prod  
#  datasource:
#    url: jdbc:mysql://localhost/tacocloud
#    username: tacouser
#    password: tacopassword
#    driver-class-name: com.mysql.jdbc.Driver
    
# logging:
#  level:
#    root: INFO
#    com.example: WARN
